#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif
#define _POSIX_C_SOURCE
#define _DEFAULT_SOURCE
#include <assert.h>
#include <complex.h>
#include <ctype.h>
#include <errno.h>
#include <fenv.h>
#include <float.h>
#include <inttypes.h>
#include <iso646.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <signal.h>
#include <stdalign.h>
#include <stdarg.h>
//#include <stdatomic.h>
#include <semaphore.h>
#include <netdb.h>
// #include <stdbit.h>
#include <stdbool.h>
// #include <stdckdint.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdnoreturn.h>
#include <string.h>
#include <tgmath.h>
#include <threads.h>
#include <time.h>
#include <uchar.h>
#include <wchar.h>
#include <wctype.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/ipc.h>
#include <sys/msg.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/un.h>
#include <sys/utsname.h>
#include <sys/wait.h>
#include <termios.h>
#include <unistd.h>
#include <alloca.h>
#include <arpa/inet.h>
#include <dirent.h>
#include <grp.h>
#include <ifaddrs.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <pwd.h>
#include <malloc.h>
#include <sys/auxv.h>
#include <sys/epoll.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/personality.h>
#include <sys/prctl.h>
#include <sys/reboot.h>
#include <sys/resource.h>
#include <sys/sendfile.h>
#include <sys/signalfd.h>
#include <sys/statfs.h>
#include <sys/sysinfo.h>
#include <sys/syslog.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <sys/utsname.h>
#include <syslog.h>
#include <termios.h>
#include <time.h>
#include <utime.h>
#include <utmp.h>
#include <bsd/bitstring.h>
#include <bsd/bsd.h>
#include <bsd/err.h>
#include <bsd/getopt.h>
#include <bsd/inttypes.h>
#include <bsd/libutil.h>
#include <bsd/md5.h>
#include <bsd/netinet/ip_icmp.h>
#include <bsd/nlist.h>
#include <bsd/readpassphrase.h>
#include <bsd/stdio.h>
#include <bsd/stdlib.h>
#include <bsd/string.h>
#include <bsd/stringlist.h>
#include <bsd/sys/bitstring.h>
#include <bsd/sys/cdefs.h>
#include <bsd/sys/endian.h>
#include <bsd/sys/param.h>
#include <bsd/sys/poll.h>
#include <bsd/sys/queue.h>
#include <bsd/sys/time.h>
#include <bsd/sys/tree.h>
#include <bsd/timeconv.h>
#include <bsd/unistd.h>
// #include <bsd/vis.h>
#include <bsd/wchar.h>
#include <search.h>

